plugins {
    id 'com.android.application'
}

android {
    namespace 'com.kurupdevs.myos'
    compileSdk 34

    defaultConfig {
        applicationId 'com.kurupdevs.myos'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        debug {
        }
        release {
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
